config/routes.rb
Rails.application.routes.draw do

  resources :categories
  root to: 'pages#home'

  devise_for :users
  resources :users, only: [:show]
  resources :events do
    resources :registrations, only: [:create]
  end
  resources :profiles, only: [:new, :edit, :create, :update]

  get "about" => "pages#about"
  get "terms_and_conditions" => "pages#terms_and_conditions"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :events


end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  validate  :end_date_cannot_be_less_than_1_day_after_start_date

 def end_date_cannot_be_less_than_1_day_after_start_date
   return unless ends_at.present? && starts_at.present?
   if  ends_at < (starts_at + 1.day)
     errors.add(:ends_at, "must be at least 1 day after start date")
   end
 end

  def bargain?
    price < 15
  end

  def self.order_by_price
    order(:price)
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  before_save :set_total_price

  def set_total_price
    price = event.price
    total = price * guests_count
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event


  def has_profile?
    profile.present? && !profile.id.nil?
  end

  def full_name
    profile.full_name
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: "New event made."
    else render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event succesfully upated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
  def set_event
    @event =  Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.all
  end

  def about
  end

  def terms_and_conditions
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @registration = current_user.registrations.new(registration_params.merge(event_id: params[:event_id]))
    @registration.set_total_price
    @registration.save
    redirect_to root_path, notice: "Thank you for registering!"
  end

  private

  def registration_params
    params.require(:registration).permit(:event_id, :status, :price, :guests_count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= render 'validation_errors' %>

<%= form_for @event do |f| %>
<div class="form-group">
  <label>Event Name</label>
  <%= f.text_field :name, placeholder: "Event Name", class: "form-control" %>
</div>

<div class="form-group">
  <label>Description</label>
  <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
</div>

<div class="form-group">
  <label>Event Location</label>
  <%= f.text_field :location, placeholder: "Event Location", class: "form-control" %>
</div>

<div class="form-group">
  <label>Start Date</label>
  <p><%= f.datetime_select :starts_at, class: "form-control" %></p>
</div>

<div class="form-group">
  <label>End date</label>
  <p> <%= f.datetime_select :ends_at,  class: "form-control" %></p>
  </%>
</div>

<label>Free shit</label>

<div class="form-group">
  <%= f.check_box :includes_drinks %> Includes drinks
</div>
<div class="form-group">
  <%= f.check_box :includes_food %> Includes food
</div>


<label>Categories</label>
<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>



<label>Publish this Event?</label>

<div class="form-group">
  <%= f.check_box :active %> Active
</div>

<div class="actions">
  <%= f.submit "Save", class: "btn btn-primary" %>
</div>
<% end %>

app/views/events/_validation_errors.html.erb
<ul>
  <% @event.errors.full_messages.each do | message | %>
    <li><%= message %></li>
    <% end %>
</ul>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">
        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-6">
            <h4><%= event.name%></h4>
          </div>
          <div class="col-md-4 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
            <%= link_to "Delete", event_path(event.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add new Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">


    <!-- Main Info -->
    <h4>Event Information</h4>
    <p><%= @event.name %></p>
    <p><%= @event.description %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Free shit</h4>
    <ul class="amenities">
      <li><%= !@event.includes_drinks ? ("<s>Free drinks</s>").html_safe : "Free drinks" %></li>
      <li><%= !@event.includes_food ? ("<s>Free food</s>").html_safe : "Free food" %></li>
    </ul>

    <h4>Categories</h4>
    <ul class="amenities">
      <% @categories.each do |category| %>
      <li><%= category.name %></li>
      <% end %>
    </ul>
  </div>
</div>

<% if current_user != @event.user %>
<div class="panel panel-primary">
  <div class="panel-heading">Book this room</div>

  <div class="panel-body">
    <%= render 'registrations/form' %>
  </div>
</div>
<% end %>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="push">
    <div class="container">
    <%= yield %>
    </div>
  </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-9">
    <p>This page was built in 2017</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        All Events
      </div>
      <div class="panel-body">
          <% @events.each do |event| %>
          <div class="row">
            <div class="col-md-6">
              <h4><%= event.name%></h4>
            </div>
            <div class="col-md-4 right">
              <%= link_to "View", event, class: "btn btn-default" %>
              <% if current_user == event.user %>
              <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
              <%= link_to "Delete", event_path(event.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
          <% end %>

        </div>


      </div>
    </div>

    <%= link_to "Your events", events_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/pages/terms_and_conditions.html.erb
These are the terms and conditions

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer navbar-fixed-bottom navbar-default">
  <div class="container">
    <p class="text-muted text-center"> <%= link_to "Terms and Conditions.", terms_and_conditions_path %></p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- _navbar.html.erb -->

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.has_profile? ? current_user.profile.full_name : current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "View your Events", events_path %></li>
              <li role="separator" class="divider"></li>
              <% if current_user.has_profile? %>
                    <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
                  <% else %>
                    <li><%= link_to "Create Profile", new_profile_path %></li>
                  <% end %>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>